# Generated by Django 6.0.5 on 2026-05-09 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Karta (oxirgi 4 raqam)')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Tranzaksiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
