# Generated by Django 6.0.5 on 2026-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Janr nomi')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kino nomi')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='Asl nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Trailer URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube/embed)')),
                ('year', models.IntegerField(verbose_name='Yili')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Rejissor')),
                ('actors', models.TextField(blank=True, verbose_name='Aktyorlar')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'Full HD'), ('4K', '4K Ultra HD')], default='HD', max_length=10, verbose_name='Sifat')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium kino')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Reyting')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre', verbose_name='Janrlar')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
